# Generated by Django 4.0.2 on 2022-02-14 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesId', models.CharField(max_length=50)),
                ('question', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='answer', serialize=False, to='api.question')),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='options', serialize=False, to='api.question')),
                ('optionA', models.CharField(max_length=200)),
                ('optionB', models.CharField(max_length=200)),
                ('optionC', models.CharField(max_length=200)),
                ('optionD', models.CharField(max_length=200)),
            ],
        ),
    ]
