# Generated by Django 4.0.2 on 2022-02-15 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedAnswer',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='submission', serialize=False, to='api.question')),
                ('submitedAnswer', models.CharField(max_length=50)),
            ],
        ),
    ]
